# Generated by Django 4.2.1 on 2023-05-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacations',
            new_name='Vacation',
        ),
    ]
