# Generated by Django 4.2.1 on 2023-05-25 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_vacations_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Approved_vacation_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='Remaining_vacation_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='Employee_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.employee'),
        ),
    ]
