# Generated by Django 4.2.1 on 2023-05-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_employee_approved_vacation_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='Status',
            field=models.TextField(default='Submitted'),
        ),
    ]
